spring.datasource.url=jdbc:mysql://localhost:3306/complaintbox
spring.datasource.username=complaint_app
spring.datasource.password=root555
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true